name: Deploy Prod

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync project to production directory (exclude compose)
        run: |
          rsync -av --delete \
            --exclude=docker-compose-prod.yml \
            ./ ~/17th-team1-client/

      - name: Stop existing containers
        run: |
          cd ~/17th-team1-client
          docker compose -f docker-compose-prod.yml down || true

      - name: Rebuild & start containers
        run: |
          cd ~/17th-team1-client
          docker compose -f docker-compose-prod.yml up -d --build
